services:
  minfo:
    build: .
    privileged: true
    ports:
      - "28081:8080"
    environment:
      PORT: "8080"
      WEB_PASSWORD: "adminadmin"
      REQUEST_TIMEOUT: "20m"
    volumes:
      - /your/media/path1:/media_path1:ro
      - /your/media/path2:/media_path2:ro
      - /your/media/path3:/media_path3:ro
      - /your/media/path4:/media_path4:ro
    restart: unless-stopped
